
  frequency: 60
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.5
  print_diagnostics: true
  publish_tf: true

  odom_frame: odom
  base_link_frame: base_footprint

  world_frame: odom

  odom0: odom
  odom0_config: [true, true, false,                                                                                  
                 false, false, true,
                 true, false, true,
                 false, false, true,
                 false, false, false]

  odom0_queue_size: 10
  odom0_differential: true

  imu0: imu/data
  imu0_config: [false, false, false,
                false, false, false,
                false, false, false,
                false, false, true,
                false, false, false]
  imu0_queue_size: 10
  imu0_differential: true
  imu0_remove_gravitational_acceleration: true
  imu0_linear_acceleration_rejection_threshold: 0.8

